header = '#dp'
newline = '\n'
space = ' '
character = 'a' | 'b' | 'c' | ... | 'x' | 'y' | 'z' | 'A' | 'B' | 'C' | ... | 'X' | 'Y' | 'Z' | space | '_'
name = character { character }
path = '"' name { '/' name } '"'
argument = '"' name '"'
path-command = 'path:' space path
inc-command = 'inc:' space path { argument }
file = header newline path-command newline inc-command { newline inc-command }
